openapi: 3.0.0
info:
  title: KarateTools Open Api - Basic
  version: 1.0.0
  contact:
    name: Karate Tools
    email: karatetools@inditex.com
  description: KarateTools Open Api - Basic
servers:
- url: http://localhost:8080/karatetools
  description: Local
security:
  - basicAuth: [ ]
  - bearerAuth: [ ]
tags:
- name: BasicApi
paths:
  /items:
    get:
      summary: List all items
      description: List all items
      operationId: listItems
      tags:
      - BasicApi
      parameters:
      - name: limit
        in: query
        description: How many items to return at one time (max 100)
        required: false
        schema:
          type: integer
          maximum: 100
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Items'
              example:
                - id: 1
                  name: Item1
                  tag: Tag1
                - id: 2
                  name: Item2
        '400':
          description: invalid parameters
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 404
                message: Not Found
                stack: Item with id 0 not found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                message: Unauthorized
                stack: User not authorized
    post:
      summary: Create an item
      description: Create an item
      operationId: createItems
      tags:
      - BasicApi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/Item'
            example:
              id: 1
              name: Item1
              tag: Tag1
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Item'
              example:
                id: 1
                name: Item1
                tag: Tag1
        '400':
          description: invalid item
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 400
                message: Bad Request
                stack: Error creating item
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                message: Unauthorized
                stack: User not authorized
  /items/{itemId}:
    get:
      summary: Info for a specific item
      description: Info for a specific item
      operationId: showItemById
      tags:
      - BasicApi
      parameters:
      - name: itemId
        in: path
        required: true
        description: The id of the item to retrieve
        schema:
          type: integer
          format: int32
        example:
          1
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Item'
              example:
                id: 1
                name: Item1
                tag: Tag1
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 404
                message: Not Found
                stack: Item with id 0 not found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                message: Unauthorized
                stack: User not authorized
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
